# Generated by Django 5.0.4 on 2024-05-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_user_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proname', models.CharField(max_length=60)),
                ('protype', models.CharField(default='', max_length=30)),
                ('qty', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('prodetail', models.TextField()),
                ('pro_picture', models.ImageField(default='', upload_to='profile_picture/')),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='fname',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='contact',
            name='lname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='usertype',
            field=models.CharField(default='buyer', max_length=60),
        ),
    ]
